### ISSUE TITLE
Onboarding To-Do list

### ISSUE THREAD

**Issue by vv-monsalve** [smc/Gayathri#11]
This would be the To-Do list for the onboarding process for Gayathri.

- [ ] Solve the remaining Fails: [Google Fonts Latin Core coverage](https://github.com/smc/Gayathri/issues/2); [License file name](https://github.com/smc/Gayathri/issues/3#issuecomment-767943997).
- [ ] Inspect the [Warns](https://github.com/smc/Gayathri/issues/7) and ensure the reported is ok in Gayathri. Particularly the ones about GDEF table.
- [ ] Review Outline Quality Checklist and ensure everything is ok. Some of the reported Warns are related to it.
- [ ] Review/adjust [the spacing and kerning](https://github.com/smc/Gayathri/issues/8)
- [ ] Include the [Bio information](https://github.com/smc/Gayathri/issues/5) for the Designer Catalog.

**Comment by vv-monsalve** [comment]
Reported Fail after `v1.220` fonts

<details><summary>🔥 <b>FAIL:</b> Check OFL body text is correct. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/license/OFL_body_text">com.google.fonts/check/license/OFL_body_text</a>)</summary><div>

>
>Check OFL body text is correct. Often users will accidently delete parts of the body text.
>
* 🔥 **FAIL** The OFL.txt body text is incorrect. Please use https://github.com/googlefonts/Unified-Font-Repository/blob/main/OFL.txt as a template. You should only modify the first line. [code: incorrect-ofl-body-text]
</div></details>

License URL should be https://scripts.sil.org/OFL

**Comment by vv-monsalve** [comment]
### New To-Do list updated after `v1.220` fonts



- [ ] Solve the remaining Fails: [Google Fonts Latin Core coverage](https://github.com/smc/Gayathri/issues/2); OFL (see above comment)
- [ ] Inspect the [Warns](https://github.com/smc/Gayathri/issues/7#issuecomment-1333026051) and ensure the reported is ok in Gayathri. Particularly the ones about GDEF table 
- [ ] Review/adjust [the spacing and kerning](https://github.com/smc/Gayathri/issues/8) 
- [ ] Inspect and solve the changes on the [diffenator report](https://github.com/smc/Gayathri/issues/9#issuecomment-1333016996)

**Comment by santhoshtr** [comment]
>FAIL: Check OFL body text is correct. ([com.google.fonts/check/license/OFL_body_text](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/license/OFL_body_text))

Fixed in 018f9c4abc7dd5a8e380039f25599491ae5400ea

**Comment by santhoshtr** [comment]
[New version 1.230 has these fixes](https://gitlab.com/smc/fonts/gayathri/-/releases/Version1.230)

**Comment by vv-monsalve** [comment]
Hi @santhoshtr, the copyright year in the fonts (2022) differs to the year in OFL.txt (2023).

Otoh, the reported regression on diacritic marks is still present in the font. Some are heavier now and missaligned.

![Gayathri1230-marks](https://user-images.githubusercontent.com/48698976/230502520-4aeb0a5c-7665-4802-8563-345d006f66f7.gif)

![diffbrowsers_text-macOS-12 6 3-x86_64-i386-64bit_chrome_111 0 5563 146](https://user-images.githubusercontent.com/48698976/230502524-41ff2038-0063-409e-8ad3-d910b55e9a1a.gif)

**Comment by santhoshtr** [comment]
Hi @vv-monsalve,

> Hi @santhoshtr, the copyright year in the fonts (2022) differs to the year in OFL.txt (2023).

Fixed in d2e826c002887a9629a9bbc6a784ec650896d0ef, available in a minor release [Version1.231](https://gitlab.com/smc/fonts/gayathri/-/releases/Version1.231)

> Otoh, the reported regression on diacritic marks is still present in the font. Some are heavier now and missaligned.

This is expected from the bug fix aefe9f11cb48eb1bde993443409747dc3e7d5800. 

Gayathri won't have any more updates on these latin glyphs, we will fix only major bugs if any for the primary script(Malayalam).

* Gayathri is primarily a Malayalam typeface. To servce the Malayalam speaking demography, all of our fonts has basic English support too. But latin, extended latin are best effort basis and mostly for the requirements of Google fonts.
*  There is no incentives of any kind to fine tune that glyphset or known serious users
* Gayathri was designed in 2018 and designer is not actively working on it

I hope this clarifies and we will be able to update this verion in Google fonts so that it can be reintroduced in Google drive. Thanks.
